#!/bin/bash
SCRIPT_NAME="./03"
ORIG_KEY="/org_con"
ACTUAL_KEY="/actual_cron"
if ! [ -f "$ORIG_KEY" ]
then
	md5sum /etc/crontab > "$ORIG_KEY"
fi
touch "$ACTUAL_KEY"
md5sum /etc/crontab > "$ACTUAL_KEY"
if [ "$(cat $ACTUAL_KEY)" != "$(cat $ORIG_KEY)" ]
then
	echo "Your crontab file has been modified." |  mail -s "!! WARNING CRONTAB !!" root
fi
rm "$ACTUAL_KEY" "$ORIG_KEY"
md5sum /etc/crontab > "$ORIG_KEY"
chmod 777 "$SCRIPT_NAME"
#echo "@daily sh $SCRIPT_NAME" | crontab
